### ISSUE TITLE
[Suggestion] Allow The Showing/Hiding Of "Ban Appeal" In The Nav Bar

### ISSUE THREAD

**Issue by MuhsinunCool** [partydragen/BanAppeal#6]
Title says it all. There shud be a button that allows u to toggle showing it in the nav bar and there shud also be an easy way to change the text it says. I looked in ur language file and the initialisation.php file and commented out the nav bar portion so I could disable it :P

EDIT:
Here's the code I'm using to show the Ban Appeal button in the footer if anyone else wants to use it:
initialisation.php:

<?php 
/*
-  Made by Partydragen
-  http://partydragen.com/
  *
-  License: MIT
  */

// Initialise the ban appeal addon
// We've already checked to see if it's enabled

require('addons/BanAppeal/language.php');

// Enabled, add links to navbar

// Enable Nav Bar
// $navbar_array[] = array('banappeal' => $banappeal_language['ban_appeal_icon'] . $banappeal_language['ban_appeal']);

// Enable Footer
$footer_nav_array['banappeal'] = $banappeal_language['ban_appeal_icon'] . $banappeal_language['ban_appeal'];
$custom_mod_sidebar['banappeal'] = array(
    'url' => '/mod/banappeal',
    'title' => $banappeal_language['ban_appeal']
);

EDIT 2: I can't use the code tags for some reason o3o

**Comment by samerton** [comment]
@partydragen 
This can be marked as closed now :)
